apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-flask-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment-flask-app
  template:
    metadata:
      labels:
        app: deployment-flask-app
    spec:
      containers:
        - name: flask-app
          image: maksymtarnavskyi/simple-app:latest
          ports:
          - containerPort: 5000
