# This is a basic workflow to help you get started with Actions

name: CI-WEEK-3

on:
  push:
    branches:
      - 'week3-wanb-logging'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_MAIN_NAME: nlp-sample
  IMAGE_MAIN_TAG: latest

jobs:
  cml-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - name: Train model
        run: |
          docker build -f week3/nlp-sample/Dockerfile -t nlp-sample:latest week-3/nlp-sample
          docker run -v $PWD:/tmp/results -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} nlp-sample:latest make train_fast_ci
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          # cat results.txt >> report.md
          cml send-comment README.md

